### ISSUE TITLE
August 2020

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#75]
|date | time | location|
|:--:|:--:|:--:|
|August 8, 2020 JST | 14:00-16:30 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2020/2020-08-10.md)

## Agenda

- 技術書典 9
- Vivliostyle Pub

### クレジットカードによる寄付金募集ページを準備中

- [テストページについての報告（#advisors）](https://vivliostyle.slack.com/archives/G015NCWN94Y/p1595433359220700)
- 課題が若干残っている
    - GitHubスポンサーのリード原稿
    - 英語ページ用のタイトル原稿
     - 英語ページの作成
     - 自動課金の停止用ID/PWの設定
     - 支援者Twitterアイコンの取得ワークフロー
     - 決済フォームのカスタマイズ（[ヘッダーにロゴを埋め込む等](https://jpayment.zendesk.com/hc/ja/articles/360000167501-%E6%B1%BA%E6%B8%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0-%E3%83%98%E3%83%83%E3%83%80%E3%83%BC-%E7%AE%A1%E7%90%86%E7%94%BB%E9%9D%A2-%E8%A8%AD%E5%AE%9A-%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)）
    - その他校正
- Create Book のページ作成が終わり次第、作業再開の予定

### Create Book のチュートリアルページを制作中

- [日本語ページ](https://paper.dropbox.com/doc/--A5MKRBY03it5pM4~ezlY4pzSAQ-ROZz55PMxvj2FGb6zWSWJ)
- [英語ページ](https://paper.dropbox.com/doc/Tutorial-Guide--A5NiURXEnRe8nrCcMSB1ZL5QAQ-6wJYRLDZTQxftFDYyvzzf)

### 技術書典 9に向けCreate Book の特集企画ページを制作中

- [Create Bookで同人誌を作ろう！](https://paper.dropbox.com/doc/Create-Book--A5QMd5tpowQ4VBP9O~6cwt8TAQ-aTsekKIXFcqsJvHiLMRpN)

## Create Book

create-book issues
https://github.com/vivliostyle/create-book/issues

- [ ] `description` notation should be `title` https://github.com/vivliostyle/create-book/issues/8
- [ ] workDir or distDir?   https://github.com/vivliostyle/create-book/issues/5
- [ ] Non-ASCII characters in directory name  https://github.com/vivliostyle/create-book/issues/7
- [ ] Should we recommend `npx create-book <directory>` or with Yarn 2 `yarn dlx create-book <directory>` https://github.com/vivliostyle/create-book/issues/9
- [ ] Rename create-book to create-vivliostyle-project https://github.com/vivliostyle/create-book/issues/4

## CLI

vivliostyle-cli issues
https://github.com/vivliostyle/vivliostyle-cli/issues

- Regression from v2.1.0
  - [ ] Error on EPUB (unzipped) loading (v3.0.0-pre.2)   https://github.com/vivliostyle/vivliostyle-cli/issues/63
  - [ ] WebBook support in v3   https://github.com/vivliostyle/vivliostyle-cli/issues/64
- [ ] Generating publication manifest should be optional   https://github.com/vivliostyle/vivliostyle-cli/issues/65
- [ ] W3C Publication Manifest or Readium Web Publication Manifest?   https://github.com/vivliostyle/vivliostyle-cli/issues/67
- [ ] Should keep existing options such as `-t` and `--output`   https://github.com/vivliostyle/vivliostyle-cli/issues/60
- [ ] toc.html generation option   https://github.com/vivliostyle/vivliostyle-cli/issues/66
- [ ] Stylesheet load error "404 http://localhost:13000/artifacts/style.css"   https://github.com/vivliostyle/vivliostyle-cli/issues/62
- [ ] EPUB support   https://github.com/vivliostyle/vivliostyle-cli/issues/55
- [ ] Add --grayscale option   https://github.com/vivliostyle/vivliostyle-cli/issues/44
- [ ] Replace preview UI with Vivliostyle Viewer   https://github.com/vivliostyle/vivliostyle-cli/issues/41
- [ ] Need to post-fix PDF for Japanese/Chinese text accessibility   https://github.com/vivliostyle/vivliostyle-cli/issues/40
- [ ] Can't load from Web URL   https://github.com/vivliostyle/vivliostyle-cli/issues/15
- [ ] An error occurs when preview quit   https://github.com/vivliostyle/vivliostyle-cli/issues/16

## VFM

vfm issues
https://github.com/vivliostyle/vfm/issues

- Math notation
  - [ ] spec: Math notation https://github.com/vivliostyle/vfm/issues/18
  - [ ] Processor-independent math output https://github.com/vivliostyle/vfm/issues/30
  - [ ] Math equation でイタリック、上付き文字がパースされない https://github.com/vivliostyle/vfm/issues/36
  - [ ] Behavior of break lines inside inlineMath is strange  https://github.com/vivliostyle/vfm/issues/31
- [ ] spec: Footnotes https://github.com/vivliostyle/vfm/issues/33
- [ ] Language default should be undefined, not 'en'  https://github.com/vivliostyle/vfm/issues/34
- [ ] spec: `<figure>` for image container  https://github.com/vivliostyle/vfm/issues/15
- etc. many open issues! https://github.com/vivliostyle/vfm/issues

## Themes

themes issues
https://github.com/vivliostyle/themes/issues

- [ ] How to customize the style of themes?   https://github.com/vivliostyle/themes/issues/9
- [ ] Finalize categories   https://github.com/vivliostyle/themes/issues/2
- [ ] Add theme for academic paper, journal, and thesis   https://github.com/vivliostyle/themes/issues/1

## Full minutes

**Present:**
- @MurakamiShinyu
- @ogwata
- @yamasy1549
- @takanakahiko
- @akabekobeko

**Regrets:**

**Scribe:** @akabekobeko

**Comment by ogwata** [comment]
今月の活動報告をまとめてみました。
- [活動報告（2020年7月19日-8月8日）](https://paper.dropbox.com/doc/2020719-88--A5ReZKO3ELWy7fNvgYopdEF_AQ-M7xXaJAQYOIYp37R3c16T)

**Comment by MurakamiShinyu** [comment]
## Open issues on Create Book

### create-book issues
https://github.com/vivliostyle/create-book/issues

- [ ] `description` notation should be `title` https://github.com/vivliostyle/create-book/issues/8
- [ ] workDir or distDir?   https://github.com/vivliostyle/create-book/issues/5
- [ ] Non-ASCII characters in directory name  https://github.com/vivliostyle/create-book/issues/7
- [ ] Should we recommend `npx create-book <directory>` or with Yarn 2 `yarn dlx create-book <directory>` https://github.com/vivliostyle/create-book/issues/9
- [ ] Rename create-book to create-vivliostyle-project https://github.com/vivliostyle/create-book/issues/4

### vivliostyle-cli issues
https://github.com/vivliostyle/vivliostyle-cli/issues
- Regression from v2.1.0
  - [ ] Error on EPUB (unzipped) loading (v3.0.0-pre.2)   https://github.com/vivliostyle/vivliostyle-cli/issues/63
  - [ ] WebBook support in v3   https://github.com/vivliostyle/vivliostyle-cli/issues/64
- [ ] Generating publication manifest should be optional   https://github.com/vivliostyle/vivliostyle-cli/issues/65
- [ ] W3C Publication Manifest or Readium Web Publication Manifest?   https://github.com/vivliostyle/vivliostyle-cli/issues/67
- [ ] Should keep existing options such as `-t` and `--output`   https://github.com/vivliostyle/vivliostyle-cli/issues/60
- [ ] toc.html generation option   https://github.com/vivliostyle/vivliostyle-cli/issues/66
- [ ] Stylesheet load error "404 http://localhost:13000/artifacts/style.css"   https://github.com/vivliostyle/vivliostyle-cli/issues/62
- [ ] EPUB support   https://github.com/vivliostyle/vivliostyle-cli/issues/55
- [ ] Add --grayscale option   https://github.com/vivliostyle/vivliostyle-cli/issues/44
- [ ] Replace preview UI with Vivliostyle Viewer   https://github.com/vivliostyle/vivliostyle-cli/issues/41
- [ ] Need to post-fix PDF for Japanese/Chinese text accessibility   https://github.com/vivliostyle/vivliostyle-cli/issues/40
- [ ] Can't load from Web URL   https://github.com/vivliostyle/vivliostyle-cli/issues/15
- [ ] An error occurs when preview quit   https://github.com/vivliostyle/vivliostyle-cli/issues/16

### vfm issues
https://github.com/vivliostyle/vfm/issues

- Math notation
  - [ ] spec: Math notation https://github.com/vivliostyle/vfm/issues/18
  - [ ] Processor-independent math output https://github.com/vivliostyle/vfm/issues/30
  - [ ] Math equation でイタリック、上付き文字がパースされない https://github.com/vivliostyle/vfm/issues/36
  - [ ] Behavior of break lines inside inlineMath is strange  https://github.com/vivliostyle/vfm/issues/31
- [ ] spec: Footnotes https://github.com/vivliostyle/vfm/issues/33
- [ ] Language default should be undefined, not 'en'  https://github.com/vivliostyle/vfm/issues/34
- [ ] spec: `<figure>` for image container  https://github.com/vivliostyle/vfm/issues/15
- etc. many open issues! https://github.com/vivliostyle/vfm/issues

### themes issues
https://github.com/vivliostyle/themes/issues

- [ ] How to customize the style of themes?   https://github.com/vivliostyle/themes/issues/9
- [ ] Finalize categories   https://github.com/vivliostyle/themes/issues/2
- [ ] Add theme for academic paper, journal, and thesis   https://github.com/vivliostyle/themes/issues/1

**Comment by akabekobeko** [comment]
@ogwata @MurakamiShinyu いただいたコメントをアジェンダへ反映させました。

**Comment by ogwata** [comment]
@akabekobeko 

私の活動報告ですが、書く前は報告すべきことがたくさんあると思っていましたが、まとめてみると親項目が3つにまとまりました。

そのまま投稿してしまいましたが、この程度なら文書を引用する形にせず、内容を取り込んでいただいた方が読む人に親切かもしれません。いかがでしょう？

**Comment by akabekobeko** [comment]
@ogwata 確かにそのほうが読むためのステップも減ってよいですね。リンク先を元にそうしてみました。

**Comment by akabekobeko** [comment]
Issue 上に Markdown でコメントがあれば、それをそのままコピペできます。なので次回また開発者会議 Issue を立てた場合は議題について直にコメントしていただけると助かります。

**Comment by akabekobeko** [comment]
本イベントを開催して議事録に Issue リンクを掲載したので close します。

**Comment by akabekobeko** [comment]
議事録を付け忘れたので re-open

**Comment by akabekobeko** [comment]
議事録を追加したので close
